export const GET_CURRENCIES_REQUEST: "GET_CURRENCIES_REQUEST" =
  "GET_CURRENCIES_REQUEST";
export const GET_CURRENCIES_SUCCESS: "GET_CURRENCIES_SUCCESS" =
  "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILED: "GET_CURRENCIES_FAILED" =
  "GET_CURRENCIES_FAILED";

export const SET_CURRENCY: "SET_CURRENCY" = "SET_CURRENCY";
