version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
    - .env   
    depends_on: 
      - mongodb
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
  
volumes:
  mongodb_data_container: